name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@mailstream"
      - name: Install dependencies and build 🔧
        run: npm ci && npx nx run-many --target=build
      - name: Publish SMTP package on NPM 📦
        run: npm publish
        working-directory: "./src/package/smtp"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
